env:
 - SMT=z3

# Note: the distinction between `before_install` and `install` is not important.
before_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install cabal-install-1.18 ghc-7.8.4 ocaml camlidl
 - export PATH="$HOME/.cabal/bin:/opt/ghc/7.8.4/bin:/opt/cabal/1.18/bin:$PATH"
 - cabal update
 - git clone git://github.com/ucsd-progsys/liquid-fixpoint.git /tmp/fixpoint
 - pushd /tmp/fixpoint && cabal install -fbuild-external && popd
 - git clone https://github.com/UCSD-PL/language-ecmascript.git /tmp/language-ecmascript
 - pushd /tmp/language-ecmascript && git checkout RefScript && cabal install && popd
 - curl "http://goto.ucsd.edu/~gridaphobe/$SMT" -o "$HOME/.cabal/bin/$SMT"
 - chmod a+x "$HOME/.cabal/bin/$SMT"

install:
 - cabal install --only-dependencies

script:
 - cabal configure -fdevel -O2 --enable-tests -v2  # -v2 provides useful information for debugging
 - cabal build
 - cabal copy
 - cabal register
 - ./dist/build/test/test --pattern "$TESTS/" --smtsolver "$SMT" -j1 +RTS -N2 -RTS
 - cabal check
 - cabal sdist   # tests that a source-distribution can be generated
