flags:
  liquid-fixpoint:
    build-external: true
packages:
- ./liquid-fixpoint
- '.'
extra-deps:
- ascii-progress-0.3.2.0
- concurrent-output-1.7.0
- intern-0.9.1.4
- located-base-0.1.0.0
resolver: nightly-2015-09-24
