#! /bin/bash
echo "These files are going to be deleted:"

find .  -name "*.css"   -o \
        -name "*.md"    -o \
        -name "*.vc"    -o \
        -name "*.hi"    -o \
        -name "*.out"   -o \
        -name "*.fqout" -o \
        -name "*.fq"    -o \
        -name "*.o"     -o \
        -name "*.err"   -o \
        -name "*.annot" -o \
        -name "*.log"   -o \
        -name "*.cgi"   -o \
        -name "*.smt2"   -o \
        -name "*.html"

while true; do
  read -p "Do you wish to delete the above files? " yn
  case $yn in
    [Yy]* ) find .  -name "*.css"   -o \
                    -name "*.md"    -o \
                    -name "*.vc"    -o \
                    -name "*.hi"    -o \
                    -name "*.out"   -o \
                    -name "*.fqout" -o \
                    -name "*.fq"    -o \
                    -name "*.o"     -o \
                    -name "*.err"   -o \
                    -name "*.annot" -o \
                    -name "*.log"   -o \
                    -name "*.cgi"   -o \
                    -name "*.smt2"   -o \
                    -name "*.html"  | xargs rm -rf ; exit;;
    [Nn]* ) exit;;
    * ) echo "Please answer yes or no.";;
  esac
done
